
server.port=8090
spring.application.name=api-gateway-service
spring.main.web-application-type=reactive

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true


# Authentication Service
spring.cloud.gateway.routes[0].id=authentication-service
spring.cloud.gateway.routes[0].uri=lb://authentication-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=store-keeper-service
spring.cloud.gateway.routes[1].uri=lb://store-keeper-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/store/**


secret.key=PA2PXn8s+kbn0gxkbzNfG+2ZcSNFfjIyh6P+XHHMB5g=


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG