
server.port=8090
spring.application.name=api-gateway-service
spring.main.web-application-type=reactive

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true


# Authentication Service
spring.cloud.gateway.server.webflux.routes[0].id=authentication-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://authentication-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# StoreKeeper Service
spring.cloud.gateway.server.webflux.routes[1].id=store-keeper-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://store-keeper-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/store/**


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG

app.security.jwt.public-key-path=/home/lemonsthedev/soloprojects/MjengoCMS/apigatewayservice/ApiGateway-Service/src/main/resources/keys/public-secret.pem